/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jDsMibWCXX8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { ToggleGroupItem, ToggleGroup } from "~/components/ui/toggle-group"
import { Text } from "~/components/ui/text"

export default function LandOfferType() {
  return (
    <div>
      <ToggleGroup className="rounded-md p-2 flex items-center gap-2" type="multiple">
        <ToggleGroupItem
          aria-label="Show All Lands"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="all"
        >
          <Text>All</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Lands for Buy"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="buy"
        >
          <Text>Buy</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Lands For Rent"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="rent"
        >
          <Text>Rent</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Sold Lands"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="sold"
        >
          <Text>Sold</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Land from Agent"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="agents"
        >
          <Text>Agents</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Land from Owners"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="owners"
        >
          <Text>Owners</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="With Due Diligence"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="due_deligence"
        >
          <Text>Deligence</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="With Photos"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="photos"
        >
          <Text>Photos</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="With Videos"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="videos"
        >
          <Text>Videos</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="View"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="view"
        >
          <Text>View</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Near Ocean"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="near_ocean"
        >
          <Text>Ocean</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Near River"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="near_river"
        >
          <Text>River</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Road Accees"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="road_access"
        >
          <Text>Road</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Electricity"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="electricity"
        >
          <Text>Electricity</Text>
        </ToggleGroupItem>
        <ToggleGroupItem
          aria-label="Water Access"
          className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800"
          value="water"
        >
          <Text>Water</Text>
        </ToggleGroupItem>
      </ToggleGroup>
    </div>
  )
}
// From Agents/Owners
// With Due Deligence
// With Videos
// With Photos
// Zones
